# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interpolation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_interpolation(object):
    def setupUi(self, interpolation):
        interpolation.setObjectName("interpolation")
        interpolation.resize(600, 238)
        interpolation.setMinimumSize(QtCore.QSize(600, 238))
        self.buttonBox = QtWidgets.QDialogButtonBox(interpolation)
        self.buttonBox.setGeometry(QtCore.QRect(130, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 29))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 121, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 29))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 29))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 170, 202, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 29))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(210, 10, 221, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(210, 170, 221, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_7.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 90, 41, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(210, 50, 121, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_8.addWidget(self.comboBox)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 130, 202, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 29))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(210, 130, 121, 31))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(['IDW', 'Kriging'])
        self.verticalLayout_10.addWidget(self.comboBox_2)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(480, 10, 101, 31))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_11)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_11.addWidget(self.pushButton)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(interpolation)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(480, 170, 101, 31))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_12)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)

        self.retranslateUi(interpolation)
        # self.buttonBox.accepted.connect(interpolation.accept)
        # self.buttonBox.rejected.connect(interpolation.reject)
        QtCore.QMetaObject.connectSlotsByName(interpolation)

    def retranslateUi(self, interpolation):
        _translate = QtCore.QCoreApplication.translate
        interpolation.setWindowTitle(_translate("interpolation", "Interpolation algorithm"))
        self.label.setText(_translate("interpolation", "Input points"))
        self.label_2.setText(_translate("interpolation", "Attribute column"))
        self.label_3.setText(_translate("interpolation", "Cellsize"))
        self.label_4.setText(_translate("interpolation", "Output inteprolated surface"))
        self.label_5.setText(_translate("interpolation", "Interpolation method"))
        self.pushButton.setText(_translate("interpolation", "Browse"))
        self.pushButton_2.setText(_translate("interpolation", "Browse"))

