# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kmeans.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kmeans(object):
    def setupUi(self, kmeans):
        kmeans.setObjectName("kmeans")
        kmeans.resize(459, 184)
        self.buttonBox = QtWidgets.QDialogButtonBox(kmeans)
        self.buttonBox.setGeometry(QtCore.QRect(100, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 102, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 29))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(120, 10, 221, 31))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(350, 10, 101, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(350, 110, 101, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(120, 110, 221, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 29))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 60, 102, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 29))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(kmeans)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(120, 60, 41, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_9.addWidget(self.spinBox)

        self.retranslateUi(kmeans)
        # self.buttonBox.accepted.connect(kmeans.accept)
        # self.buttonBox.rejected.connect(kmeans.reject)
        QtCore.QMetaObject.connectSlotsByName(kmeans)

    def retranslateUi(self, kmeans):
        _translate = QtCore.QCoreApplication.translate
        kmeans.setWindowTitle(_translate("kmeans", "Unsupervised Classification"))
        self.label.setText(_translate("kmeans", "Input DEM"))
        self.pushButton.setText(_translate("kmeans", "Browse"))
        self.pushButton_2.setText(_translate("kmeans", "Browse"))
        self.label_2.setText(_translate("kmeans", "Output KMeans classification"))
        self.label_3.setText(_translate("kmeans", "Clusters"))

