# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terrain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Terrain(object):
    def setupUi(self, Ui_Terrain):
        Ui_Terrain.setObjectName("Ui_Terrain")
        Ui_Terrain.resize(742, 212)
        Ui_Terrain.setMinimumSize(QtCore.QSize(742, 212))
        Ui_Terrain.setMaximumSize(QtCore.QSize(742, 212))
        self.buttonBox = QtWidgets.QDialogButtonBox(Ui_Terrain)
        self.buttonBox.setGeometry(QtCore.QRect(40, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 102, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 29))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 102, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 29))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 90, 102, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 29))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(130, 10, 221, 31))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(130, 50, 221, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(130, 90, 221, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_6.addWidget(self.lineEdit_5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(360, 10, 101, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(360, 50, 101, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(Ui_Terrain)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(360, 90, 101, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_9.addWidget(self.pushButton_3)

        self.retranslateUi(Ui_Terrain)
        # self.buttonBox.accepted.connect(Ui_Terrain.accept)
        # self.buttonBox.rejected.connect(Ui_Terrain.reject)
        QtCore.QMetaObject.connectSlotsByName(Ui_Terrain)

    def retranslateUi(self, Ui_Terrain):
        _translate = QtCore.QCoreApplication.translate
        Ui_Terrain.setWindowTitle(_translate("Ui_Terrain", "Terrain Analysis"))
        self.label_2.setText(_translate("Ui_Terrain", "Output Slope"))
        self.label.setText(_translate("Ui_Terrain", "Input DEM"))
        self.label_3.setText(_translate("Ui_Terrain", "Output Aspect"))
        self.pushButton.setText(_translate("Ui_Terrain", "Browse"))
        self.pushButton_2.setText(_translate("Ui_Terrain", "Browse"))
        self.pushButton_3.setText(_translate("Ui_Terrain", "Browse"))

